### ISSUE TITLE
Huya API Rate limit

### ISSUE THREAD

**Issue by alexanderkitsou** [Xmarmalade/LiveAPI#1]
Hello,
Thanks for creating this library.
Do you know what the rate limit for Huya is?

I tried looking in the headers but unless I am mistaken it doesn't return a value.

**Comment by iiijam** [comment]
I'm not sure about the rate limit of Huya's API. In my project, there seems to be no problem with sending multiple requests simultaneously.

**Comment by iiijam** [comment]
You can try this deployed on vercel https://ice-live-ldl1q61iw-iiijam.vercel.app/
